/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ShopRouteImport } from './routes/shop'
import { Route as CartRouteImport } from './routes/cart'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProductSlugRouteImport } from './routes/product.$slug'
import { Route as CollectionsCategoryRouteImport } from './routes/collections.$category'
import { Route as TexturesTextureRouteImport } from './routes/textures.$texture'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopRoute = ShopRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductSlugRoute = ProductSlugRouteImport.update({
  id: '/product/$slug',
  path: '/product/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CollectionsCategoryRoute = CollectionsCategoryRouteImport.update({
  id: '/collections/$category',
  path: '/collections/$category',
  getParentRoute: () => rootRouteImport,
} as any)
const TexturesTextureRoute = TexturesTextureRouteImport.update({
  id: '/textures/$texture',
  path: '/textures/$texture',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cart': typeof CartRoute
  '/shop': typeof ShopRoute
  '/product/$slug': typeof ProductSlugRoute
  '/collections/$category': typeof CollectionsCategoryRoute
  '/textures/$texture': typeof TexturesTextureRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cart': typeof CartRoute
  '/shop': typeof ShopRoute
  '/product/$slug': typeof ProductSlugRoute
  '/collections/$category': typeof CollectionsCategoryRoute
  '/textures/$texture': typeof TexturesTextureRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cart': typeof CartRoute
  '/shop': typeof ShopRoute
  '/product/$slug': typeof ProductSlugRoute
  '/collections/$category': typeof CollectionsCategoryRoute
  '/textures/$texture': typeof TexturesTextureRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/cart' | '/shop' | '/product/$slug' | '/collections/$category' | '/textures/$texture'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/cart' | '/shop' | '/product/$slug' | '/collections/$category' | '/textures/$texture'
  id: '__root__' | '/' | '/cart' | '/shop' | '/product/$slug' | '/collections/$category' | '/textures/$texture'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CartRoute: typeof CartRoute
  ShopRoute: typeof ShopRoute
  ProductSlugRoute: typeof ProductSlugRoute
  CollectionsCategoryRoute: typeof CollectionsCategoryRoute
  TexturesTextureRoute: typeof TexturesTextureRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop': {
      id: '/shop'
      path: '/shop'
      fullPath: '/shop'
      preLoaderRoute: typeof ShopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/product/$slug': {
      id: '/product/$slug'
      path: '/product/$slug'
      fullPath: '/product/$slug'
      preLoaderRoute: typeof ProductSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collections/$category': {
      id: '/collections/$category'
      path: '/collections/$category'
      fullPath: '/collections/$category'
      preLoaderRoute: typeof CollectionsCategoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/textures/$texture': {
      id: '/textures/$texture'
      path: '/textures/$texture'
      fullPath: '/textures/$texture'
      preLoaderRoute: typeof TexturesTextureRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CartRoute: CartRoute,
  ShopRoute: ShopRoute,
  ProductSlugRoute: ProductSlugRoute,
  CollectionsCategoryRoute: CollectionsCategoryRoute,
  TexturesTextureRoute: TexturesTextureRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
